var DataDB=[{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_01.html",Name:"86 Eighty Six",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_02.html",Name:"86 Eighty Six",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_03.html",Name:"86 Eighty Six",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_04.html",Name:"86 Eighty Six",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_05.html",Name:"86 Eighty Six",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_06.html",Name:"86 Eighty Six",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_07.html",Name:"86 Eighty Six",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_08.html",Name:"86 Eighty Six",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_09.html",Name:"86 Eighty Six",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_10.html",Name:"86 Eighty Six",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_11.html",Name:"86 Eighty Six",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/86-eighty-six/86-eighty-six_vol_12.html",Name:"86 Eighty Six",Vol:"12"},
{ Url:"https://null-library.github.io/lib/vn/one-shot/all-you-need-is-kill.html",Name:"All You Need Is Kill",Vol:""},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_01.html",Name:"Amagi Brilliant Park",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_02.html",Name:"Amagi Brilliant Park",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_03.html",Name:"Amagi Brilliant Park",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_04.html",Name:"Amagi Brilliant Park",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_05.html",Name:"Amagi Brilliant Park",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_06.html",Name:"Amagi Brilliant Park",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_07.html",Name:"Amagi Brilliant Park",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/amagi-brilliant-park/amagi-brilliant-park_vol_08.html",Name:"Amagi Brilliant Park",Vol:"08"},
{ Url:"https://null-library.github.io/lib/vn/one-shot/ame-no-hi-no-iris.html",Name:"Ame No Hi No Iris",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/angel-note.html",Name:"Angel Note",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/battle-royale.html",Name:"Battle Royale",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/belka-why-don't-you-bark.html",Name:"Belka Why Don't You Bark",Vol:""},
{ Url:"https://null-library.github.io/lib/en/black-bullet/black-bullet_vol_01.html",Name:"Black Bullet",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/black-bullet/black-bullet_vol_02.html",Name:"Black Bullet",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/black-bullet/black-bullet_vol_03.html",Name:"Black Bullet",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/black-bullet/black-bullet_vol_04.html",Name:"Black Bullet",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/black-bullet/black-bullet_vol_05.html",Name:"Black Bullet",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/black-bullet/black-bullet_vol_06.html",Name:"Black Bullet",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/black-bullet/black-bullet_vol_07.html",Name:"Black Bullet",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/one-shot/bokura-wa-dokonimo-hirakanai.html",Name:"Bokura Wa Dokonimo Hirakanai",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/boku-to-kimi-dake-ni.html",Name:"Boku To Kimi Dake Ni",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/brave-story.html",Name:"Brave Story",Vol:""},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_01.html",Name:"Bungo Stray Dogs",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_02.html",Name:"Bungo Stray Dogs",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_03.html",Name:"Bungo Stray Dogs",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_04.html",Name:"Bungo Stray Dogs",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_05.html",Name:"Bungo Stray Dogs",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_06.html",Name:"Bungo Stray Dogs",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_07.html",Name:"Bungo Stray Dogs",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/bungo-stray-dogs/bungo-stray-dogs_vol_08.html",Name:"Bungo Stray Dogs",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_01.html",Name:"Danmachi",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_02.html",Name:"Danmachi",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_03.html",Name:"Danmachi",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_04.html",Name:"Danmachi",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_05.html",Name:"Danmachi",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_06.html",Name:"Danmachi",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_07.html",Name:"Danmachi",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_08.html",Name:"Danmachi",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_09.html",Name:"Danmachi",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_10.html",Name:"Danmachi",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_11.html",Name:"Danmachi",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_12.html",Name:"Danmachi",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_13.html",Name:"Danmachi",Vol:"13"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_14.html",Name:"Danmachi",Vol:"14"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_15.html",Name:"Danmachi",Vol:"15"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_16.html",Name:"Danmachi",Vol:"16"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_17.html",Name:"Danmachi",Vol:"17"},
{ Url:"https://null-library.github.io/lib/en/danmachi/danmachi_vol_18.html",Name:"Danmachi",Vol:"18"},
{ Url:"https://null-library.github.io/lib/en/danmachi-familia-chronicle/danmachi-familia-chronicle_vol_01.html",Name:"Danmachi Familia Chronicle",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/danmachi-familia-chronicle/danmachi-familia-chronicle_vol_02.html",Name:"Danmachi Familia Chronicle",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_01.html",Name:"Date A Live",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_02.html",Name:"Date A Live",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_03.html",Name:"Date A Live",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_04.html",Name:"Date A Live",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_05.html",Name:"Date A Live",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_06.html",Name:"Date A Live",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_07.html",Name:"Date A Live",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_08.html",Name:"Date A Live",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_09.html",Name:"Date A Live",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_10.html",Name:"Date A Live",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_11.5.html",Name:"Date A Live",Vol:"11.5"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_11.html",Name:"Date A Live",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_12.html",Name:"Date A Live",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_13.html",Name:"Date A Live",Vol:"13"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_14.html",Name:"Date A Live",Vol:"14"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_15.html",Name:"Date A Live",Vol:"15"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_16.html",Name:"Date A Live",Vol:"16"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_17.html",Name:"Date A Live",Vol:"17"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_18.html",Name:"Date A Live",Vol:"18"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_19.html",Name:"Date A Live",Vol:"19"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_20.html",Name:"Date A Live",Vol:"20"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_21.html",Name:"Date A Live",Vol:"21"},
{ Url:"https://null-library.github.io/lib/en/date-a-live/date-a-live_vol_22.html",Name:"Date A Live",Vol:"22"},
{ Url:"https://null-library.github.io/lib/en/one-shot/demon-city-shinjuku.html",Name:"Demon City Shinjuku",Vol:""},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_0.html",Name:"Durarara",Vol:"0"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_01.html",Name:"Durarara",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_02.html",Name:"Durarara",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_03.html",Name:"Durarara",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_04.html",Name:"Durarara",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_05.html",Name:"Durarara",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_06.html",Name:"Durarara",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_07.html",Name:"Durarara",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_08.html",Name:"Durarara",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_09.html",Name:"Durarara",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_10.html",Name:"Durarara",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_11.html",Name:"Durarara",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_12.html",Name:"Durarara",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/durarara/durarara_vol_13.html",Name:"Durarara",Vol:"13"},
{ Url:"https://null-library.github.io/lib/en/one-shot/gekkou.html",Name:"Gekkou",Vol:""},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_01.html",Name:"Gimai Seikatsu",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_02.html",Name:"Gimai Seikatsu",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_03.html",Name:"Gimai Seikatsu",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_04.html",Name:"Gimai Seikatsu",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_05.html",Name:"Gimai Seikatsu",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_06.html",Name:"Gimai Seikatsu",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_07.html",Name:"Gimai Seikatsu",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/gimai-seikatsu/gimai-seikatsu_vol_08.html",Name:"Gimai Seikatsu",Vol:"08"},
{ Url:"https://null-library.github.io/lib/vn/one-shot/harmony.html",Name:"Harmony",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/hello-hello-and-hello.html",Name:"Hello Hello And Hello",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/hello-hello-and-hello.html",Name:"Hello Hello And Hello",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/hello-world.html",Name:"Hello World",Vol:""},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_01.html",Name:"Hensuki",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_02.html",Name:"Hensuki",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_03.html",Name:"Hensuki",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_04.html",Name:"Hensuki",Vol:"04"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_04.html",Name:"Hensuki",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_05.html",Name:"Hensuki",Vol:"05"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_05.html",Name:"Hensuki",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_06.html",Name:"Hensuki",Vol:"06"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_06.html",Name:"Hensuki",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_07.html",Name:"Hensuki",Vol:"07"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_07.html",Name:"Hensuki",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_08.html",Name:"Hensuki",Vol:"08"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_08.html",Name:"Hensuki",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_09.html",Name:"Hensuki",Vol:"09"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_09.html",Name:"Hensuki",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_10.html",Name:"Hensuki",Vol:"10"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_10.html",Name:"Hensuki",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_11.html",Name:"Hensuki",Vol:"11"},
{ Url:"https://null-library.github.io/lib/vn/hensuki/hensuki_vol_11.html",Name:"Hensuki",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_12.html",Name:"Hensuki",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_13.html",Name:"Hensuki",Vol:"13"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_14.html",Name:"Hensuki",Vol:"14"},
{ Url:"https://null-library.github.io/lib/en/hensuki/hensuki_vol_Special.html",Name:"Hensuki",Vol:"Special"},
{ Url:"https://null-library.github.io/lib/en/one-shot/himote-na-ore-ga.html",Name:"Himote Na Ore Ga",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/hoshizora-no-shita.html",Name:"Hoshizora No Shita",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/hyouka/hyouka_vol_01.html",Name:"Hyouka",Vol:"01"},
{ Url:"https://null-library.github.io/lib/vn/hyouka/hyouka_vol_02.html",Name:"Hyouka",Vol:"02"},
{ Url:"https://null-library.github.io/lib/vn/hyouka/hyouka_vol_03.html",Name:"Hyouka",Vol:"03"},
{ Url:"https://null-library.github.io/lib/vn/hyouka/hyouka_vol_04.html",Name:"Hyouka",Vol:"04"},
{ Url:"https://null-library.github.io/lib/vn/hyouka/hyouka_vol_05.html",Name:"Hyouka",Vol:"05"},
{ Url:"https://null-library.github.io/lib/vn/hyouka/hyouka_vol_06.html",Name:"Hyouka",Vol:"06"},
{ Url:"https://null-library.github.io/lib/vn/one-shot/ichigo-doumei.html",Name:"Ichigo Doumei",Vol:""},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_01.html",Name:"Isekai Maou",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_02.html",Name:"Isekai Maou",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_03.html",Name:"Isekai Maou",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_04.html",Name:"Isekai Maou",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_05.html",Name:"Isekai Maou",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_06.html",Name:"Isekai Maou",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_07.html",Name:"Isekai Maou",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_08.html",Name:"Isekai Maou",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_09.html",Name:"Isekai Maou",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_10.html",Name:"Isekai Maou",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_11.html",Name:"Isekai Maou",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_12.html",Name:"Isekai Maou",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_13.html",Name:"Isekai Maou",Vol:"13"},
{ Url:"https://null-library.github.io/lib/en/isekai-maou/isekai-maou_vol_14.html",Name:"Isekai Maou",Vol:"14"},
{ Url:"https://null-library.github.io/lib/en/one-shot/itai-no-itai-no.html",Name:"Itai No Itai No",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/joze-to-tora-to-sakana-tachi.html",Name:"Joze To Tora To Sakana Tachi",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/juni-taisen.html",Name:"Juni Taisen",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/kakushigoto.html",Name:"Kakushigoto",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/kimi-boku-ga-denwa.html",Name:"Kimi Boku Ga Denwa",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/kimi-no-hanashi.html",Name:"Kimi No Hanashi",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/kimi-no-suizou-wo-tabetai.html",Name:"Kimi No Suizou Wo Tabetai",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/kimi-to-boku-no-uta-worlds-end.html",Name:"Kimi To Boku No Uta Worlds End",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/koisuru-kiseichuu.html",Name:"Koisuru Kiseichuu",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_01.html",Name:"Kono Suba",Vol:"01"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_02.html",Name:"Kono Suba",Vol:"02"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_03.html",Name:"Kono Suba",Vol:"03"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_04.html",Name:"Kono Suba",Vol:"04"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_05.html",Name:"Kono Suba",Vol:"05"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_06.html",Name:"Kono Suba",Vol:"06"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_07.html",Name:"Kono Suba",Vol:"07"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_08.html",Name:"Kono Suba",Vol:"08"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_09.html",Name:"Kono Suba",Vol:"09"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_10.html",Name:"Kono Suba",Vol:"10"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_11.html",Name:"Kono Suba",Vol:"11"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_12.html",Name:"Kono Suba",Vol:"12"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_13.html",Name:"Kono Suba",Vol:"13"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_14.html",Name:"Kono Suba",Vol:"14"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_15.html",Name:"Kono Suba",Vol:"15"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_16.html",Name:"Kono Suba",Vol:"16"},
{ Url:"https://null-library.github.io/lib/vn/kono-suba/kono-suba_vol_17.html",Name:"Kono Suba",Vol:"17"},
{ Url:"https://null-library.github.io/lib/en/one-shot/kori-no-kuni-no-amaryillis.html",Name:"Kori No Kuni No Amaryillis",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/kotonoha-no-niwa.html",Name:"Kotonoha No Niwa",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/kotonoha-no-niwa.html",Name:"Kotonoha No Niwa",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/kumo-no-mukou.html",Name:"Kumo No Mukou",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/kuzu-to-kinka-no-qualidea.html",Name:"Kuzu To Kinka No Qualidea",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/macaron.html",Name:"Macaron",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_01.html",Name:"Mahouka Koukou",Vol:"01"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_02.html",Name:"Mahouka Koukou",Vol:"02"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_03.html",Name:"Mahouka Koukou",Vol:"03"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_04.html",Name:"Mahouka Koukou",Vol:"04"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_05.html",Name:"Mahouka Koukou",Vol:"05"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_06.html",Name:"Mahouka Koukou",Vol:"06"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_07.html",Name:"Mahouka Koukou",Vol:"07"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_08.html",Name:"Mahouka Koukou",Vol:"08"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_09.html",Name:"Mahouka Koukou",Vol:"09"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_10.html",Name:"Mahouka Koukou",Vol:"10"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_11.html",Name:"Mahouka Koukou",Vol:"11"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_12.html",Name:"Mahouka Koukou",Vol:"12"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_13.html",Name:"Mahouka Koukou",Vol:"13"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_14.html",Name:"Mahouka Koukou",Vol:"14"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_15.html",Name:"Mahouka Koukou",Vol:"15"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_16.html",Name:"Mahouka Koukou",Vol:"16"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_17.html",Name:"Mahouka Koukou",Vol:"17"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_18.html",Name:"Mahouka Koukou",Vol:"18"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_19.html",Name:"Mahouka Koukou",Vol:"19"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_20.html",Name:"Mahouka Koukou",Vol:"20"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_21.html",Name:"Mahouka Koukou",Vol:"21"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_22.html",Name:"Mahouka Koukou",Vol:"22"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_23.html",Name:"Mahouka Koukou",Vol:"23"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_24.html",Name:"Mahouka Koukou",Vol:"24"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_25.html",Name:"Mahouka Koukou",Vol:"25"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_26.html",Name:"Mahouka Koukou",Vol:"26"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_27.html",Name:"Mahouka Koukou",Vol:"27"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_28.html",Name:"Mahouka Koukou",Vol:"28"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_29.html",Name:"Mahouka Koukou",Vol:"29"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_30.html",Name:"Mahouka Koukou",Vol:"30"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_31.html",Name:"Mahouka Koukou",Vol:"31"},
{ Url:"https://null-library.github.io/lib/vn/mahouka-koukou/mahouka-koukou_vol_32.html",Name:"Mahouka Koukou",Vol:"32"},
{ Url:"https://null-library.github.io/lib/en/one-shot/mardock-scramble.html",Name:"Mardock Scramble",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/mata-onaji-yume.html",Name:"Mata Onaji Yume",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/mikkakan-no-koufuku.html",Name:"Mikkakan No Koufuku",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/mimizuku-to-yoru-no-ou.html",Name:"Mimizuku To Yoru No Ou",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/mirai.html",Name:"Mirai",Vol:""},
{ Url:"https://null-library.github.io/lib/en/nier-automata/nier-automata_vol_01.html",Name:"Nier Automata",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/nier-automata/nier-automata_vol_02.html",Name:"Nier Automata",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_01.html",Name:"No Game No Life",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_02.html",Name:"No Game No Life",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_03.html",Name:"No Game No Life",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_04.html",Name:"No Game No Life",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_05.html",Name:"No Game No Life",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_06.html",Name:"No Game No Life",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_07.html",Name:"No Game No Life",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_08.html",Name:"No Game No Life",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_09.html",Name:"No Game No Life",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_10.html",Name:"No Game No Life",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/no-game-no-life/no-game-no-life_vol_11.html",Name:"No Game No Life",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/one-shot/otogi-no-mori.html",Name:"Otogi No Mori",Vol:""},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_01.html",Name:"Overlord",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_02.html",Name:"Overlord",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_03.html",Name:"Overlord",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_04.html",Name:"Overlord",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_05.html",Name:"Overlord",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_06.html",Name:"Overlord",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_07.html",Name:"Overlord",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_08.html",Name:"Overlord",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_09.html",Name:"Overlord",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_10.html",Name:"Overlord",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_11.html",Name:"Overlord",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_12.html",Name:"Overlord",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_13.html",Name:"Overlord",Vol:"13"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_14.html",Name:"Overlord",Vol:"14"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_15.html",Name:"Overlord",Vol:"15"},
{ Url:"https://null-library.github.io/lib/en/overlord/overlord_vol_16.html",Name:"Overlord",Vol:"16"},
{ Url:"https://null-library.github.io/lib/vn/one-shot/phenomeno.html",Name:"Phenomeno",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/pygmalion-wa-tane.html",Name:"Pygmalion Wa Tane",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/riku-and-chise.html",Name:"Riku And Chise",Vol:""},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_01.html",Name:"Saijaku Muhai No Bahamut",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_02.html",Name:"Saijaku Muhai No Bahamut",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_03.html",Name:"Saijaku Muhai No Bahamut",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_04.html",Name:"Saijaku Muhai No Bahamut",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_05.html",Name:"Saijaku Muhai No Bahamut",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_06.html",Name:"Saijaku Muhai No Bahamut",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_07.html",Name:"Saijaku Muhai No Bahamut",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_08.html",Name:"Saijaku Muhai No Bahamut",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_09.html",Name:"Saijaku Muhai No Bahamut",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_10.html",Name:"Saijaku Muhai No Bahamut",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_11.html",Name:"Saijaku Muhai No Bahamut",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_12.html",Name:"Saijaku Muhai No Bahamut",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_13.html",Name:"Saijaku Muhai No Bahamut",Vol:"13"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_14.html",Name:"Saijaku Muhai No Bahamut",Vol:"14"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_15.html",Name:"Saijaku Muhai No Bahamut",Vol:"15"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_16.html",Name:"Saijaku Muhai No Bahamut",Vol:"16"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_17.html",Name:"Saijaku Muhai No Bahamut",Vol:"17"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_18.html",Name:"Saijaku Muhai No Bahamut",Vol:"18"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_19.html",Name:"Saijaku Muhai No Bahamut",Vol:"19"},
{ Url:"https://null-library.github.io/lib/en/saijaku-muhai-no-bahamut/saijaku-muhai-no-bahamut_vol_20.html",Name:"Saijaku Muhai No Bahamut",Vol:"20"},
{ Url:"https://null-library.github.io/lib/en/one-shot/sekaiichi-kantan.html",Name:"Sekaiichi Kantan",Vol:""},
{ Url:"https://null-library.github.io/lib/en/shiki/shiki_vol_01.html",Name:"Shiki",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/shiki/shiki_vol_02.html",Name:"Shiki",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/one-shot/side-by-side-dreamers.html",Name:"Side By Side Dreamers",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/starting-over.html",Name:"Starting Over",Vol:""},
{ Url:"https://null-library.github.io/lib/en/one-shot/sugar-dark.html",Name:"Sugar Dark",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/tabi-ni-deyou.html",Name:"Tabi Ni Deyou",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/one-shot/tsuki-no-sango.html",Name:"Tsuki No Sango",Vol:""},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_01.html",Name:"Uchi Musume",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_02.html",Name:"Uchi Musume",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_03.html",Name:"Uchi Musume",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_04.html",Name:"Uchi Musume",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_05.html",Name:"Uchi Musume",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_06.html",Name:"Uchi Musume",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_07.html",Name:"Uchi Musume",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_08.html",Name:"Uchi Musume",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/uchi-musume/uchi-musume_vol_09.html",Name:"Uchi Musume",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/utsuro-no-hako/utsuro-no-hako_vol_01.html",Name:"Utsuro No Hako",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/utsuro-no-hako/utsuro-no-hako_vol_02.html",Name:"Utsuro No Hako",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/utsuro-no-hako/utsuro-no-hako_vol_03.html",Name:"Utsuro No Hako",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/utsuro-no-hako/utsuro-no-hako_vol_04.html",Name:"Utsuro No Hako",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/utsuro-no-hako/utsuro-no-hako_vol_05.html",Name:"Utsuro No Hako",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/utsuro-no-hako/utsuro-no-hako_vol_06.html",Name:"Utsuro No Hako",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/utsuro-no-hako/utsuro-no-hako_vol_07.html",Name:"Utsuro No Hako",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/one-shot/yokohama-station-sf.html",Name:"Yokohama Station Sf",Vol:""},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_01.html",Name:"You Jitsu",Vol:"01"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_02.html",Name:"You Jitsu",Vol:"02"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_03.html",Name:"You Jitsu",Vol:"03"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_04.5.html",Name:"You Jitsu",Vol:"04.5"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_04.html",Name:"You Jitsu",Vol:"04"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_05.html",Name:"You Jitsu",Vol:"05"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_06.html",Name:"You Jitsu",Vol:"06"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_07.5.html",Name:"You Jitsu",Vol:"07.5"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_07.html",Name:"You Jitsu",Vol:"07"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_08.html",Name:"You Jitsu",Vol:"08"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_09.html",Name:"You Jitsu",Vol:"09"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_10.html",Name:"You Jitsu",Vol:"10"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_11.5.html",Name:"You Jitsu",Vol:"11.5"},
{ Url:"https://null-library.github.io/lib/vn/you-jitsu/you-jitsu_vol_11.html",Name:"You Jitsu",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_01.html",Name:"You Jitsu Year 2",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_02.html",Name:"You Jitsu Year 2",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_03.html",Name:"You Jitsu Year 2",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_04.5.html",Name:"You Jitsu Year 2",Vol:"04.5"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_04.html",Name:"You Jitsu Year 2",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_05.html",Name:"You Jitsu Year 2",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_06.html",Name:"You Jitsu Year 2",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/you-jitsu-year-2/you-jitsu-year-2_vol_07.html",Name:"You Jitsu Year 2",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_01.html",Name:"Youjo Senki",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_02.html",Name:"Youjo Senki",Vol:"02"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_03.html",Name:"Youjo Senki",Vol:"03"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_04.html",Name:"Youjo Senki",Vol:"04"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_05.html",Name:"Youjo Senki",Vol:"05"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_06.html",Name:"Youjo Senki",Vol:"06"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_07.html",Name:"Youjo Senki",Vol:"07"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_08.html",Name:"Youjo Senki",Vol:"08"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_09.html",Name:"Youjo Senki",Vol:"09"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_10.html",Name:"Youjo Senki",Vol:"10"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_11.html",Name:"Youjo Senki",Vol:"11"},
{ Url:"https://null-library.github.io/lib/en/youjo-senki/youjo-senki_vol_12.html",Name:"Youjo Senki",Vol:"12"},
{ Url:"https://null-library.github.io/lib/en/one-shot/yume-nikki.html",Name:"Yume Nikki",Vol:""},
{ Url:"https://null-library.github.io/lib/en/z-no-jikan/z-no-jikan_vol_01.html",Name:"Z No Jikan",Vol:"01"},
{ Url:"https://null-library.github.io/lib/en/z-no-jikan/z-no-jikan_vol_02.html",Name:"Z No Jikan",Vol:"02"},];
function pageRender() {
    var curLN = "";
    var curLNMini = "";
    var isOneShot = false;
    var lang = 'en';
    var htmlLN=""    
    var content_wrap = document.getElementById("content-wrap");
    DataDB.forEach(data=> {
        if(data.Url.includes('/one-shot/')) isOneShot=true
        else isOneShot =false;
        if(data.Url.includes('/lib/vn/')) lang='vn';
        else lang ='en';
        let volName = data.Name;

        if(curLN!= data.Name){
            content_wrap.innerHTML+=htmlLN +`</div></div>`;
            curLN=data.Name;
            curLNMini= !isOneShot?curLN.replaceAll(" ","-").toLowerCase() :"one-shot";
            if(data?.Vol!="") volName = data.Name +' - Vol '+ data?.Vol;
            htmlLN="";
            let thumbnail= !isOneShot ? (data.Name.replaceAll(" ","-")+"_Vol_").toLowerCase()+data?.Vol+"_1.jpg" : data.Name.replaceAll(" ","-").toLowerCase()+"_1.jpg";
            htmlLN+=`<div class="content__container"><div class="container__header"><div>`+data?.Name+`</div></div><hr class="separate"><div class="container__body"><div class="item-container"><a style="text-decoration:none" href=`+ data?.Url+` class="item-border"><div class="item"><div class="item-thumbnail"><div class="item-img" style="background-image:url(https://null-library.github.io/assets/thumbs/`+thumbnail+`)"></div><span class="item-rate">`+lang.toUpperCase()+`</span></div><div class="title-wrap"><div class="item-title">`+volName+`</div></div></div></a></div>`;
            
        }
        else{
            if(data?.Vol!="") volName = data.Name +' - Vol '+ data?.Vol;
            let thumbnail= !isOneShot ? (data.Name.replaceAll(" ","-")+"_Vol_").toLowerCase()+data?.Vol+"_1.jpg" : data.Name.replaceAll(" ","-").toLowerCase()+"_1.jpg";
            htmlLN+=`<div class="item-container"><a style="text-decoration:none" href=`+ data?.Url+` class="item-border"><div class="item"><div class="item-thumbnail"><div class="item-img" style="background-image:url(https://null-library.github.io/assets/thumbs/`+thumbnail+`)"><span class="item-rate">`+lang.toUpperCase()+`</span></div></div><div class="title-wrap"><div class="item-title">`+volName+`</div></div></div></a></div>`;
        
        }
    });
}
pageRender();
